name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: what-you-expected
    attributes:
      label: What you expected to happen
    validations:
      required: true
  - type: textarea
    id: resolution-acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: This will allow approvers to ensure that there is proper resolution for this bug.
      value: |
        GIVEN <pre-requisites>
        WHEN I <do some action>
        THEN I <see some outcome>
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce it (as minimally and precisely as possible)
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else we need to know?
  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: |
        Revision of codebase:
        Kubernetes version (use `kubectl version`):
        Cloud provider or hardware configuration:
        Others:
    validations:
      required: true
