name: Chore
description: Request a chore
title: "[Chore]: "
labels: [chore]
body:
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Insert helpful context and links around the pain point being felt/tech debt.
    validations:
      required: true
  - type: textarea
    id: action-to-take
    attributes:
      label: Action to take
      description: This section is optional, but if it is clear what steps should be taken, we should note them. For example, if there is already an agreed upon solution or next step(s).
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Note the expected impact of this chore. This will allow us to properly prioritize against other chores.
    validations:
      required: true
  - type: textarea
    id: dev-notes
    attributes:
      label: Dev Notes
      placeholder: This section can either be filled in advance or serves as a place to document learnings from discussion in IPM.
