name: Feature Story
description: Request a feature
title: "[Feature]: <USER> can <achieve some outcome>"
labels: [feature]
body:
  - type: textarea
    id: blockers-dependencies
    attributes:
      label: Blockers/Dependencies
      description: What blockers or dependencies exist?
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Insert any additional helpful context and links. Specifically note if the USER is an end user or API client.
      value: |
        **As a** <USER>
        **I want** <some feature>
        **So that** <I can achieve some outcome>
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Generally acceptance criteria should cover the “happy path” case as well as any edge cases.
      value: |
        **GIVEN** <pre-requisites>
        **WHEN I** <do some action>
        **THEN I** <see some outcome>
    validations:
      required: true
  - type: textarea
    id: dev-notes
    attributes:
      label: Dev Notes
      placeholder: This section can either be filled in advance or serves as a place to document learnings from discussion in IPM.
