name: PYTHON-CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./python/agileetc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: | 
          poetry env use python3
          poetry check
          poetry update
          poetry install --no-root
          poetry run flake8

  ci:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.10.5]
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./python/agileetc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: | 
          poetry env use python3
          poetry update
          poetry install
          poetry run pytest

  release:
    if: github.event_name == 'push'
    needs: ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/agileetc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: | 
          poetry update
          poetry version patch
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
          git tag $(poetry version --short)
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true